version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # all scripts and sql file inside this directory will be executed after database initialization
      - "./db/:/docker-entrypoint-initdb.d/"

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data/

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A proj worker -l info -E --pidfile /var/run/celery.pid
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    # https://docs.docker.com/compose/startup-order/
    command: ./wait-for-it.sh db:5432 -- celery -A proj beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile /var/run/celerybeat.pid
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  celery-flower:
    build: .
    command: celery -A proj flower --port=5555 --loglevel=info # --persistent=True
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data:
